
#server.port=${LOCAL_PORT:8080}
server.port=8090

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=${LOCAL_SPRING_DATASOURCE_URL}
spring.datasource.username=${LOCAL_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${LOCAL_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#security configs
#spring.security.user.name=manish
#spring.security.user.password=pass

jwt.secretKey=${JWT_SECRET} 

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Max file size 10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.tomcat.max-part-count=100